# kubectl -n futbol create secret generic futbol-db \
#   --from-literal=dsn="host=futbol-db.lab dbname=futbol user=futbol password=CHANGE_ME"
apiVersion: v1
kind: Secret
metadata: { name: futbol-db, namespace: futbol }
type: Opaque
stringData:
  dsn: "host=futbol-db.lab dbname=futbol user=futbol password=CHANGE_ME"
