"""
Does dropping xG from the props feature set produce better MLS predictions?

READ-ONLY. Issues SELECTs and nothing else. Trains models in memory, writes
no artifacts, touches no ledger.

    python scripts/compare_props_features.py --market CORNERS
    python scripts/compare_props_features.py --market SOT
    python scripts/compare_props_features.py --market all

WHY
team_match_stats.xg is 100% populated for EPL/SERIE_A (Understat) and 0%
populated for MLS (API-Football's tier does not supply it). fit_props_model
selects xg_for_r5 / xg_against_r5 and then calls dropna(), so every MLS row is
silently discarded. MLS props are therefore generated by a model trained only
on English and Italian football, scored on MLS fixtures where those two
features arrive as NaN. LightGBM accepts NaN, so nothing ever errored.

WHAT IT MEASURES
  A. Is xG earning its place at all? Train on EPL+SERIE_A only, with and
     without xG, evaluate on the same held-out European rows. If the two are
     level, xG costs nothing to drop.

  B. The question that actually matters. Evaluate on held-out MLS rows:
       - current   : trained on EPL+SERIE_A with xG, scored on MLS (xG = NaN)
       - proposed  : trained on EPL+SERIE_A+MLS without xG
     Whichever wins decides the feature set for the model-artifact work.

Both against a naive baseline (train-set mean), matching the "must beat a
naive baseline on held-out data" bar the project already sets for props.

Holdout is the most recent 20% of rows per league by kickoff, so every league
contributes test rows despite MLS and the European leagues running on
different calendars.
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd
import psycopg2
from scipy.stats import poisson

try:
    import lightgbm as lgb
except ImportError:
    sys.exit("lightgbm is required: pip install lightgbm")

DSN = os.environ.get("FUTBOL_DSN", "host=futbol-db dbname=futbol user=futbol")

BASE_FEATURES = ["shots_for_r5", "shots_against_r5", "rest_days", "is_home"]
XG_FEATURES = ["xg_for_r5", "xg_against_r5"]

MARKETS = {
    "CORNERS": {"target": "corners",
                "own": ["corners_for_r5", "corners_against_r5"]},
    "SOT": {"target": "shots_on_target",
            "own": ["sot_for_r5", "sot_against_r5"]},
}

LGB_PARAMS = dict(objective="poisson", n_estimators=300, learning_rate=0.03,
                  num_leaves=20, min_child_samples=30, subsample=0.8,
                  colsample_bytree=0.8, verbose=-1)

HOLDOUT_FRACTION = 0.20


def load(conn, market: str) -> pd.DataFrame:
    spec = MARKETS[market]
    cols = spec["own"] + BASE_FEATURES + XG_FEATURES
    select = ", ".join(f"f.{c}" for c in cols)
    sql = f"""
        SELECT l.code AS league, f.kickoff_utc, {select},
               tms.{spec['target']} AS y
        FROM futbol.team_match_features f
        JOIN futbol.leagues l ON l.league_id = f.league_id
        JOIN futbol.team_match_stats tms
          ON tms.match_id = f.match_id AND tms.team_id = f.team_id
        WHERE tms.{spec['target']} IS NOT NULL
        ORDER BY f.kickoff_utc
    """
    with conn.cursor() as cur:
        cur.execute(sql)
        rows = cur.fetchall()
        names = [d[0] for d in cur.description]
    df = pd.DataFrame(rows, columns=names)
    for c in cols + ["y"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["is_home"] = df["is_home"].astype(float)
    return df


def split(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Most recent HOLDOUT_FRACTION of each league's rows, by kickoff."""
    train, test = [], []
    for _, grp in df.groupby("league", sort=False):
        grp = grp.sort_values("kickoff_utc")
        cut = int(len(grp) * (1 - HOLDOUT_FRACTION))
        train.append(grp.iloc[:cut])
        test.append(grp.iloc[cut:])
    return pd.concat(train), pd.concat(test)


def poisson_logloss(y: np.ndarray, mu: np.ndarray) -> float:
    mu = np.clip(mu, 1e-6, None)
    return float(-poisson.logpmf(y, mu).mean())


def fit(train: pd.DataFrame, features: list[str]):
    d = train.dropna(subset=features + ["y"])
    if d.empty:
        return None, 0
    model = lgb.LGBMRegressor(**LGB_PARAMS)
    model.fit(d[features], d["y"])
    return model, len(d)


def evaluate(model, test: pd.DataFrame, features: list[str],
             baseline_mu: float) -> dict | None:
    """Rows missing a feature are kept: LightGBM treats NaN as missing, which
    is exactly what happens in production today."""
    d = test.dropna(subset=["y"])
    if d.empty or model is None:
        return None
    mu = np.clip(model.predict(d[features]), 1e-6, None)
    return {
        "n": len(d),
        "logloss": poisson_logloss(d["y"].to_numpy(), mu),
        "mae": float(np.abs(d["y"].to_numpy() - mu).mean()),
        "baseline_logloss": poisson_logloss(
            d["y"].to_numpy(), np.full(len(d), baseline_mu)),
        "baseline_mae": float(np.abs(d["y"].to_numpy() - baseline_mu).mean()),
    }


def row(label: str, r: dict | None) -> str:
    if r is None:
        return f"  {label:<34} (no data)"
    delta = r["baseline_logloss"] - r["logloss"]
    verdict = "beats baseline" if delta > 0 else "WORSE than baseline"
    return (f"  {label:<34} n={r['n']:<6} logloss={r['logloss']:.4f}  "
            f"MAE={r['mae']:.3f}  ({verdict} by {delta:+.4f})")


def run(conn, market: str) -> None:
    spec = MARKETS[market]
    with_xg = spec["own"] + BASE_FEATURES + XG_FEATURES
    no_xg = spec["own"] + BASE_FEATURES

    df = load(conn, market)
    print(f"\n{'=' * 78}\n{market} — target `{spec['target']}`\n{'=' * 78}")
    print("Rows available per league (and how many carry xG):")
    for league, grp in df.groupby("league"):
        n_xg = int(grp[XG_FEATURES].notna().all(axis=1).sum())
        print(f"  {league:<10} {len(grp):>6} rows, {n_xg:>6} with xG "
              f"({100.0 * n_xg / max(len(grp), 1):.1f}%)")

    train, test = split(df)
    europe = ["EPL", "SERIE_A"]
    train_eu = train[train["league"].isin(europe)]
    test_eu = test[test["league"].isin(europe)]
    test_mls = test[test["league"] == "MLS"]

    baseline_eu = train_eu["y"].mean()
    baseline_all = train["y"].mean()

    # --- A: is xG earning its place, judged only where it exists? ---
    print("\nA. Does xG help, on European rows where it is present?")
    m_with, n_with = fit(train_eu, with_xg)
    m_without, n_without = fit(train_eu, no_xg)
    print(f"   (trained on EPL+SERIE_A: {n_with} rows with xG, "
          f"{n_without} without)")
    print(row("with xG    -> EU holdout", evaluate(m_with, test_eu, with_xg, baseline_eu)))
    print(row("without xG -> EU holdout", evaluate(m_without, test_eu, no_xg, baseline_eu)))

    # --- B: which model is actually better at MLS? ---
    print("\nB. Which model predicts MLS better?")
    m_all, n_all = fit(train, no_xg)
    print(f"   (proposed model trains on all leagues without xG: {n_all} rows, "
          f"vs {n_with} for the current Europe-only model)")
    print(row("CURRENT  EU+xG -> MLS holdout",
              evaluate(m_with, test_mls, with_xg, baseline_all)))
    print(row("PROPOSED all,no-xG -> MLS holdout",
              evaluate(m_all, test_mls, no_xg, baseline_all)))
    print("\n  Lower logloss is better. The CURRENT row is what production does\n"
          "  today: a model that never saw MLS, scoring MLS with xG as NaN.")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--market", default="all", choices=["CORNERS", "SOT", "all"])
    args = ap.parse_args()
    markets = list(MARKETS) if args.market == "all" else [args.market]

    conn = psycopg2.connect(DSN)
    try:
        for m in markets:
            run(conn, m)
    finally:
        conn.close()
    print()


if __name__ == "__main__":
    main()
