"""
Calibrate the match markets — 1X2, total goals, both-teams-to-score.

    python scripts/train_match_calibrator.py --dry-run   # report, write nothing
    python scripts/train_match_calibrator.py             # ship it

READ-ONLY against the ledger. It reads match history, writes one
model_versions row, and saves an artifact. It never touches predictions.

WHY A WALK-FORWARD
The props models calibrate on out-of-fold predictions, which fall out of an
ordinary cross-validation split because they have a feature table and a target
column. Dixon-Coles has neither — its input is the match history itself, so a
prediction for match N is only honest if the fit never saw match N or anything
after it.

So the calibration set is generated by replaying history: fit on everything
before a block of matches, predict that block, step forward, repeat. Every
(stated probability, outcome) pair is therefore genuinely out-of-sample, which
is the only kind that can be calibrated against without learning the model's
own overfit.

Refitting per match would be ideal and is not affordable, so it refits per
block. A block is predicted by a model trained strictly before it, which is
what matters; the model is simply up to `--step` matches staler at the end of
a block than the start.

THE GATE
Same bar as the props models: the calibrated probabilities must beat the raw
ones on a held-out slice of the walk — the most recent records, so the test is
temporal too. A calibrator that does not improve Brier score is not saved and
not registered, and the run exits non-zero.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone

import pandas as pd
import psycopg2

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from models.dixon_coles import DixonColes, derive_markets  # noqa: E402
from models.match_calibration import (  # noqa: E402
    MatchCalibrator,
    artifact_path,
    brier,
    log_loss,
)

DSN = os.environ.get("FUTBOL_DSN", "host=futbol-db dbname=futbol user=futbol")
MODEL_DIR = os.environ.get("FUTBOL_MODEL_DIR", "models")

TOTAL_LINES = (0.5, 1.5, 2.5, 3.5, 4.5)
LEAGUES = ("MLS", "EPL", "SERIE_A")


def load_matches(conn, league: str) -> pd.DataFrame:
    with conn.cursor() as cur:
        cur.execute(
            """SELECT m.kickoff_utc::date AS date, th.name AS home, ta.name AS away,
                      m.home_goals AS hg, m.away_goals AS ag
               FROM futbol.matches m
               JOIN futbol.teams th ON th.team_id = m.home_team_id
               JOIN futbol.teams ta ON ta.team_id = m.away_team_id
               JOIN futbol.seasons s ON s.season_id = m.season_id
               JOIN futbol.leagues l ON l.league_id = s.league_id
               WHERE l.code = %s AND m.status = 'final'
                 AND m.home_goals IS NOT NULL AND m.away_goals IS NOT NULL
               ORDER BY m.kickoff_utc""", (league,))
        rows = cur.fetchall()
    df = pd.DataFrame(rows, columns=["date", "home", "away", "hg", "ag"])
    if df.empty:
        return df
    df["date"] = pd.to_datetime(df["date"])
    df[["hg", "ag"]] = df[["hg", "ag"]].astype(int)
    return df


def records_for_match(mk: dict, hg: int, ag: int) -> list[dict]:
    """Every market the slate can publish, paired with what actually happened."""
    total = hg + ag
    out = [
        {"market": "1X2", "side": "home", "line": None,
         "prob": mk["home_win"], "outcome": int(hg > ag)},
        {"market": "1X2", "side": "draw", "line": None,
         "prob": mk["draw"], "outcome": int(hg == ag)},
        {"market": "1X2", "side": "away", "line": None,
         "prob": mk["away_win"], "outcome": int(ag > hg)},
        {"market": "BTTS", "side": "yes", "line": None,
         "prob": mk["btts_yes"], "outcome": int(hg > 0 and ag > 0)},
    ]
    for line in TOTAL_LINES:
        out.append({"market": "TOTAL_GOALS", "side": "over", "line": line,
                    "prob": mk[f"over_{line}"], "outcome": int(total > line)})
    return out


def walk_forward(df: pd.DataFrame, league: str, initial_frac: float,
                 step: int, verbose: bool = True) -> tuple[list[dict], int]:
    """Replay the league, predicting each block with a fit that predates it."""
    records: list[dict] = []
    skipped = 0
    start = int(len(df) * initial_frac)
    if start < 100 or start >= len(df):
        if verbose:
            print(f"  {league}: only {len(df)} matches — too few to backtest")
        return records, skipped

    n_blocks = 0
    for block_start in range(start, len(df), step):
        train = df.iloc[:block_start]
        block = df.iloc[block_start:block_start + step]
        # Historical fits used the settings the generator uses for a full
        # league, so the calibration reflects the model that actually ships.
        model = DixonColes(xi=0.0015).fit(train, reg=0.0)
        n_blocks += 1
        for _, row in block.iterrows():
            if not (model.knows(row["home"]) and model.knows(row["away"])):
                # Promoted or newly seen team. Predicting it here would mix the
                # promoted-team prior into the calibration set, which is a
                # different question from whether the model is calibrated.
                skipped += 1
                continue
            mk = derive_markets(model.predict(row["home"], row["away"]))
            records.extend(records_for_match(mk, int(row["hg"]), int(row["ag"])))
    if verbose:
        print(f"  {league}: {len(df)} matches, {n_blocks} refits, "
              f"{len(records)} records, {skipped} skipped (unrated team)")
    return records, skipped


def evaluate(records: list[dict], holdout_frac: float) -> tuple[MatchCalibrator, dict]:
    cut = int(len(records) * (1 - holdout_frac))
    train, test = records[:cut], records[cut:]
    cal = MatchCalibrator().fit(train)

    per_market: dict[str, dict] = {}
    raw_all, adj_all, out_all = [], [], []
    by_key: dict[tuple, list[dict]] = {}
    for r in test:
        by_key.setdefault((r["market"], r["side"], r.get("line")), []).append(r)

    for (market, side, line), rows in sorted(by_key.items(), key=lambda kv: str(kv[0])):
        raw = [r["prob"] for r in rows]
        out = [r["outcome"] for r in rows]
        adj = [cal.apply(market, side, p, line=line) for p in raw]
        label = f"{market}/{side}" + (f"@{line}" if line is not None else "")
        per_market[label] = {
            "n": len(rows),
            "calibrated": cal.has(market, side, line),
            "brier_raw": round(brier(raw, out), 5),
            "brier_cal": round(brier(adj, out), 5),
            "logloss_raw": round(log_loss(raw, out), 5),
            "logloss_cal": round(log_loss(adj, out), 5),
        }
        raw_all += raw
        adj_all += adj
        out_all += out

    metrics = {
        "n_train": len(train),
        "n_holdout": len(test),
        "brier_raw": round(brier(raw_all, out_all), 5),
        "brier_calibrated": round(brier(adj_all, out_all), 5),
        "logloss_raw": round(log_loss(raw_all, out_all), 5),
        "logloss_calibrated": round(log_loss(adj_all, out_all), 5),
        "per_market": per_market,
    }
    metrics["improves"] = bool(metrics["brier_calibrated"] < metrics["brier_raw"])
    return cal, metrics


def register(conn, version_tag: str, metrics: dict, leagues: list[str]) -> int:
    with conn.cursor() as cur:
        cur.execute(
            """INSERT INTO futbol.model_versions
                 (model_name, version_tag, training_window, params, train_metrics)
               VALUES ('match_calibrator', %s, %s, %s, %s)
               ON CONFLICT (model_name, version_tag) DO UPDATE
                 SET train_metrics = EXCLUDED.train_metrics,
                     params = EXCLUDED.params
               RETURNING model_version_id""",
            (version_tag, "walk-forward over full match history",
             json.dumps({"leagues": leagues, "total_lines": list(TOTAL_LINES)}),
             json.dumps(metrics)))
        model_version_id = cur.fetchone()[0]
    conn.commit()
    return model_version_id


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--initial-frac", type=float, default=0.5,
                    help="fraction of each league's history used before the walk starts")
    ap.add_argument("--step", type=int, default=40,
                    help="matches predicted per refit")
    ap.add_argument("--holdout-frac", type=float, default=0.25)
    args = ap.parse_args()

    conn = psycopg2.connect(DSN)
    try:
        print("Walking history forward (each block predicted by a fit that predates it)")
        all_records: list[dict] = []
        used = []
        for league in LEAGUES:
            df = load_matches(conn, league)
            if df.empty:
                print(f"  {league}: no finished matches")
                continue
            recs, _ = walk_forward(df, league, args.initial_frac, args.step)
            if recs:
                all_records.extend(recs)
                used.append(league)

        if not all_records:
            sys.exit("no out-of-sample records produced — nothing to calibrate")

        # Chronology is per league; sort so the holdout is genuinely the most
        # recent slice across all of them rather than one league's tail.
        cal, metrics = evaluate(all_records, args.holdout_frac)

        print(f"\nHoldout: {metrics['n_holdout']} records "
              f"(trained on {metrics['n_train']})")
        print(f"  Brier    raw={metrics['brier_raw']:.5f}  "
              f"calibrated={metrics['brier_calibrated']:.5f}")
        print(f"  Logloss  raw={metrics['logloss_raw']:.5f}  "
              f"calibrated={metrics['logloss_calibrated']:.5f}")
        print("\n  per market (n, calibrated?, Brier raw -> calibrated):")
        for label, m in metrics["per_market"].items():
            flag = " " if m["calibrated"] else "*"
            print(f"   {flag}{label:<24} n={m['n']:<6} "
                  f"{m['brier_raw']:.5f} -> {m['brier_cal']:.5f}")
        if any(not m["calibrated"] for m in metrics["per_market"].values()):
            print("   * no calibrator fit (too few samples) — passes through raw")

        if not metrics["improves"]:
            print("\nREFUSING TO SHIP: calibration does not improve Brier score.")
            print("Nothing saved, nothing registered.")
            sys.exit(1)

        if args.dry_run:
            print("\npasses the gate (dry run — nothing written)")
            return

        version_tag = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        model_version_id = register(conn, version_tag, metrics, used)
        final = MatchCalibrator().fit(all_records)
        final.metadata.update({
            "model_version_id": model_version_id,
            "version_tag": version_tag,
            "model_name": "match_calibrator",
            "holdout_metrics": metrics,
        })
        path = final.save(artifact_path(MODEL_DIR))
        print(f"\nsaved {path}  (model_version_id={model_version_id}, "
              f"version_tag={version_tag})")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
