"""
Calibration for the match markets: 1X2, total goals, both-teams-to-score.

WHY THIS EXISTS
Dixon-Coles produces a scoreline distribution, and derive_markets sums cells of
it into market probabilities. Those numbers are internally consistent but not
calibrated: they inherit whatever the Poisson approximation gets wrong, which
is systematically worst in the tails. The props models have been calibrated
since they were rebuilt; the match markets — the ones people actually read —
were still publishing raw model output.

WHY IT IS SHAPED DIFFERENTLY FROM PropsModel
A props model has a feature table and a target column, so out-of-fold
predictions fall out of a normal cross-validation split. Dixon-Coles has
neither: its "features" are the match history itself, and a prediction for
match N is only honest if the model never saw matches N and later. The
calibration set therefore has to be generated by walking forward through
history — see scripts/train_match_calibrator.py — and this module only knows
how to fit and apply calibrators to the (stated probability, outcome) pairs
that walk produces.

WHAT IT CALIBRATES
Each market/side pair is treated as its own binary problem and gets its own
isotonic regression:

    ("1X2", "home"), ("1X2", "draw"), ("1X2", "away"),
    ("TOTAL_GOALS", "over", 2.5), ("BTTS", "yes"), ...

Isotonic is monotone, so it cannot reorder two predictions — a fixture the raw
model preferred stays preferred. It only moves the level.

The three 1X2 outcomes are calibrated independently and then renormalised, so
they still sum to 1. Renormalising after calibration is a small compromise:
each is individually calibrated, and the rescaling nudges them off that. The
alternative — publishing three probabilities for the same match that do not sum
to 1 — is worse, since the fixture page shows them together. The training
script measures the calibrated-and-renormalised numbers, so the reported
improvement is of what actually ships, not of an intermediate.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from sklearn.isotonic import IsotonicRegression

try:
    import joblib
except ImportError:  # pragma: no cover - ships with scikit-learn
    joblib = None

ARTIFACT_VERSION = 1

# Below this an isotonic fit is describing noise, so the raw probability is
# used unchanged rather than corrected by something itself uncertain.
MIN_CALIBRATION_SAMPLES = 200

ONE_X_TWO_SIDES = ("home", "draw", "away")


def market_key(market: str, side: str, line: float | None) -> tuple:
    return (market, side, None if line is None else float(line))


@dataclass
class MatchCalibrator:
    calibrators: dict[tuple, IsotonicRegression] = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)

    # ---------- training ----------

    def fit(self, records: list[dict]) -> "MatchCalibrator":
        """
        `records` are out-of-sample predictions produced by the walk-forward:
        {"market", "side", "line", "prob", "outcome"} where outcome is 1/0.
        """
        grouped: dict[tuple, list[tuple[float, int]]] = defaultdict(list)
        for r in records:
            grouped[market_key(r["market"], r["side"], r.get("line"))].append(
                (float(r["prob"]), int(r["outcome"])))

        skipped: dict[str, str] = {}
        for key, pairs in grouped.items():
            probs = np.array([p for p, _ in pairs])
            outcomes = np.array([o for _, o in pairs])
            if len(pairs) < MIN_CALIBRATION_SAMPLES:
                skipped[str(key)] = f"only {len(pairs)} samples"
                continue
            if len(np.unique(outcomes)) < 2:
                skipped[str(key)] = "only one outcome observed"
                continue
            iso = IsotonicRegression(out_of_bounds="clip", y_min=0.01, y_max=0.99)
            iso.fit(probs, outcomes)
            self.calibrators[key] = iso

        self.metadata.update({
            "artifact_version": ARTIFACT_VERSION,
            "trained_at": datetime.now(timezone.utc).isoformat(),
            "n_records": len(records),
            "calibrated": sorted(str(k) for k in self.calibrators),
            "skipped": skipped,
            "sample_counts": {str(k): len(v) for k, v in grouped.items()},
        })
        return self

    # ---------- inference ----------

    def has(self, market: str, side: str, line: float | None = None) -> bool:
        return market_key(market, side, line) in self.calibrators

    def apply(self, market: str, side: str, prob: float,
              line: float | None = None) -> float:
        """Calibrated probability, or the input unchanged when no calibrator
        was fit for this market. Never silently substitutes a different one."""
        iso = self.calibrators.get(market_key(market, side, line))
        if iso is None:
            return float(prob)
        return float(np.clip(iso.predict([prob])[0], 0.01, 0.99))

    def apply_1x2(self, home: float, draw: float, away: float) -> tuple[float, float, float]:
        """
        Calibrate the three outcomes and renormalise so they still sum to 1.

        Falls back to the raw triple if any single calibrator is missing —
        mixing a calibrated outcome with a raw one and then renormalising would
        distort both, and a partly-corrected triple is harder to reason about
        than an uncorrected one.
        """
        if not all(self.has("1X2", s) for s in ONE_X_TWO_SIDES):
            return home, draw, away
        vals = [self.apply("1X2", s, p)
                for s, p in zip(ONE_X_TWO_SIDES, (home, draw, away))]
        total = sum(vals)
        if total <= 0:
            return home, draw, away
        return tuple(v / total for v in vals)  # type: ignore[return-value]

    # ---------- persistence ----------

    def save(self, path: str | Path) -> Path:
        if joblib is None:
            raise RuntimeError("joblib is required to persist a MatchCalibrator")
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self, path)
        return path

    @classmethod
    def load(cls, path: str | Path) -> "MatchCalibrator":
        if joblib is None:
            raise RuntimeError("joblib is required to load a MatchCalibrator")
        obj = joblib.load(Path(path))
        if not isinstance(obj, cls):
            raise TypeError(f"{path} does not contain a MatchCalibrator")
        stored = obj.metadata.get("artifact_version")
        if stored != ARTIFACT_VERSION:
            raise ValueError(
                f"{path} was written by artifact version {stored!r}, this code "
                f"expects {ARTIFACT_VERSION}. Retrain rather than loading it."
            )
        return obj


def artifact_path(model_dir: str | Path) -> Path:
    return Path(model_dir) / "match_calibrator.joblib"


# ---------- scoring ----------

def brier(probs: np.ndarray, outcomes: np.ndarray) -> float:
    return float(np.mean((np.asarray(probs) - np.asarray(outcomes)) ** 2))


def log_loss(probs: np.ndarray, outcomes: np.ndarray) -> float:
    p = np.clip(np.asarray(probs, dtype=float), 1e-9, 1 - 1e-9)
    o = np.asarray(outcomes, dtype=float)
    return float(-np.mean(o * np.log(p) + (1 - o) * np.log(1 - p)))
